### ISSUE TITLE
Wasn't able to build pywrapfst

### ISSUE THREAD

**Issue by widdiot** [BUTSpeechFIT/OOV-recovery-in-hybrid-ASR-system#2]
I tried to follow the instructions to build the pywrapfst extension but it gave me the following error log:
Im using openfst 1.6.5 and ubuntu 18.04
[log.txt](https://github.com/BUTSpeechFIT/OOV-recovery-in-hybrid-ASR-system/files/6530342/log.txt)

Can you please help?

**Comment by kate-egorova** [comment]
There are several type errors, can you please make sure you're using all the recommended builds for python, openfst, etc. ? This wasn't tested to compile on current versions

**Comment by widdiot** [comment]
Yes, I had made sure the openfst version 1.6.5, and python version 3.5 as mentioned in the readme

**Comment by kate-egorova** [comment]
The first error I can see is missing RmEpsilon so I would look into Openfst installation if the path is correct and if it installed properly
